server:
  port: 8051

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test-user?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Hongkong&useSSL=true
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

dubbo:
  application:
    name: user-provider #dubbo注册的服务名,唯一性
  registry:
    address: zookeeper://127.0.0.1:2181 #注册zookeeper的地址
  provider:
    filter: ExceptionFilter,-exception

mybatis-plus:
  check-config-location: true
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
